pipeline {
    agent {
        docker {
            image 'docker.io/golang:1.22.3'
            args '-v /home/jenkins/agent/repo:${WORKSPACE}/repo'
        }
    }

    options {
        skipDefaultCheckout()
    }

    triggers {
        pollSCM('')
    }

    stages {
        stage('Checkout') {
            steps {
                sh 'if [ ! -d ${WORKSPACE}/repo ]; then exit 1; else echo "Checkout successful."; fi'
            }
        }
    }
}
