pipeline {
    agent {
        docker 'docker.io/golang:1.22.3'
        args '-v /home/jenkins/agent/repo:${WORKSPACE}/repo'
    }

    options {
        skipDefaultCheckout()
    }

    stages {
        stage('Checkout to repository') {
            steps {
                sh 'ls -lA ${WORKSPACE}/repo'
            }
        }
    }
}
